# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.retrieval.acgc_pb import acgc_pb2 as acgc__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in acgc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ACGCServiceStub:
    """---------------------------------------------------------------------------
    ACGC gRPC Service
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Run = channel.unary_unary(
                '/acgc.v1.ACGCService/Run',
                request_serializer=acgc__pb2.RunRequest.SerializeToString,
                response_deserializer=acgc__pb2.RunResponse.FromString,
                _registered_method=True)
        self.CaptureEvent = channel.unary_unary(
                '/acgc.v1.ACGCService/CaptureEvent',
                request_serializer=acgc__pb2.CaptureEventRequest.SerializeToString,
                response_deserializer=acgc__pb2.CaptureEventResponse.FromString,
                _registered_method=True)
        self.GetState = channel.unary_unary(
                '/acgc.v1.ACGCService/GetState',
                request_serializer=acgc__pb2.GetStateRequest.SerializeToString,
                response_deserializer=acgc__pb2.GetStateResponse.FromString,
                _registered_method=True)
        self.TriggerGC = channel.unary_unary(
                '/acgc.v1.ACGCService/TriggerGC',
                request_serializer=acgc__pb2.TriggerGCRequest.SerializeToString,
                response_deserializer=acgc__pb2.TriggerGCResponse.FromString,
                _registered_method=True)
        self.GetMetrics = channel.unary_unary(
                '/acgc.v1.ACGCService/GetMetrics',
                request_serializer=acgc__pb2.GetMetricsRequest.SerializeToString,
                response_deserializer=acgc__pb2.GetMetricsResponse.FromString,
                _registered_method=True)


class ACGCServiceServicer:
    """---------------------------------------------------------------------------
    ACGC gRPC Service
    ---------------------------------------------------------------------------

    """

    def Run(self, request, context):
        """Full intercept-compile-forward cycle.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CaptureEvent(self, request, context):
        """Capture a single event (lower-level usage).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Inspect the current state tree for a session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerGC(self, request, context):
        """Manually trigger garbage collection for a session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """Get token savings and other metrics for a session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ACGCServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Run': grpc.unary_unary_rpc_method_handler(
                    servicer.Run,
                    request_deserializer=acgc__pb2.RunRequest.FromString,
                    response_serializer=acgc__pb2.RunResponse.SerializeToString,
            ),
            'CaptureEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.CaptureEvent,
                    request_deserializer=acgc__pb2.CaptureEventRequest.FromString,
                    response_serializer=acgc__pb2.CaptureEventResponse.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=acgc__pb2.GetStateRequest.FromString,
                    response_serializer=acgc__pb2.GetStateResponse.SerializeToString,
            ),
            'TriggerGC': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerGC,
                    request_deserializer=acgc__pb2.TriggerGCRequest.FromString,
                    response_serializer=acgc__pb2.TriggerGCResponse.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=acgc__pb2.GetMetricsRequest.FromString,
                    response_serializer=acgc__pb2.GetMetricsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'acgc.v1.ACGCService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('acgc.v1.ACGCService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ACGCService:
    """---------------------------------------------------------------------------
    ACGC gRPC Service
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def Run(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/acgc.v1.ACGCService/Run',
            acgc__pb2.RunRequest.SerializeToString,
            acgc__pb2.RunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CaptureEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/acgc.v1.ACGCService/CaptureEvent',
            acgc__pb2.CaptureEventRequest.SerializeToString,
            acgc__pb2.CaptureEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/acgc.v1.ACGCService/GetState',
            acgc__pb2.GetStateRequest.SerializeToString,
            acgc__pb2.GetStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerGC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/acgc.v1.ACGCService/TriggerGC',
            acgc__pb2.TriggerGCRequest.SerializeToString,
            acgc__pb2.TriggerGCResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/acgc.v1.ACGCService/GetMetrics',
            acgc__pb2.GetMetricsRequest.SerializeToString,
            acgc__pb2.GetMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
